// Generated by Wrangler
// This file simplifies development by providing types for the Worker's environment

export interface Env {
  // Add your environment variables and bindings here
  // Example:
  // API_KEY: string;
  // KV_NAMESPACE: KVNamespace;
  ASSETS: {
    fetch(request: Request | string): Promise<Response>;
  };
  RESEND_API_KEY: string;
  ENVIRONMENT?: string;
  NOTIFICATION_EMAIL?: string;
}

// Cloudflare Workers global types
declare global {
  interface Fetcher {
    fetch(request: Request | string): Promise<Response>;
  }
} 