# Cloudflare Workers configuration
name = "momentum-business-capital-landing"
main = "src/worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Enable observability logging
[observability.logs]
enabled = true

[assets]
directory = "./dist/client"
binding = "ASSETS"

# Default environment (production)
[vars]
ENVIRONMENT = "production"

# Development environment
[env.dev]
name = "momentum-business-capital-app-dev"
vars = { ENVIRONMENT = "development" }

[env.dev.assets]
directory = "./dist/client"
binding = "ASSETS"

# Production environment  
[env.production]
name = "momentum-business-capital-landing"
vars = { ENVIRONMENT = "production" }

[env.production.assets]
directory = "./dist/client"
binding = "ASSETS"

# Add these environment variables to your wrangler.toml
# You'll need to set the actual values using `wrangler secret put <NAME>`

[env.production.vars]
ENVIRONMENT = "production"

[env.development.vars]
ENVIRONMENT = "development"

# Secret variables (use `wrangler secret put DOCUSEAL_API_KEY` to set)
# DOCUSEAL_API_KEY = "your-docuseal-api-key"
# DOCUSEAL_TEMPLATE_ID = "your-template-id"
# RESEND_API_KEY = "your-resend-api-key" 