# Cloudflare Workers configuration
name = "momentum-business-capital-landing"
main = "src/worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Enable observability logging
[observability.logs]
enabled = true

[assets]
directory = "./dist/client"
binding = "ASSETS"

# Default environment (production)
[vars]
ENVIRONMENT = "production"

# Development environment
[env.dev]
name = "momentum-business-capital-app-dev"
vars = { ENVIRONMENT = "development" }

[env.dev.assets]
directory = "./dist/client"
binding = "ASSETS"

# Production environment  
[env.production]
name = "momentum-business-capital-landing"
vars = { ENVIRONMENT = "production" }

[env.production.assets]
directory = "./dist/client"
binding = "ASSETS"

# Secrets are managed via GitHub Actions and wrangler secret put commands:
# RESEND_API_KEY = "your-resend-api-key" 