# Cloudflare Workers configuration
name = "momentum-business-capital-landing"
main = "src/worker/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist/client"
binding = "ASSETS"

# Environment variables (optional)
[vars]
ENVIRONMENT = "development"
# NOTIFICATION_EMAIL will be set as a secret

# Secrets (manage via dashboard or wrangler secret put)
# RESEND_API_KEY = "your-resend-api-key"
# NOTIFICATION_EMAIL = "leads@momentumbusiness.capital" 