name = "mbc-landing-page"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Configuration for Cloudflare Pages
pages_build_output_dir = "dist"

[env.production]
name = "mbc-landing-page"

# Email configuration is now in functions/config.ts
# Only the SendGrid API key needs to be set as a secret in Cloudflare dashboard 