name = "mbc-form-handler"
main = "src/index.ts"
compatibility_date = "2024-01-15"

# Environment variables for email configuration
# Update NOTIFICATION_EMAIL with your actual email address
# SENDGRID_API_KEY = "your-sendgrid-api-key"  
# NOTIFICATION_EMAIL = "your-email@domain.com"  # <-- Update this with your email
# FROM_EMAIL = "noreply@yourdomain.com"

# Example:
# NOTIFICATION_EMAIL = "admin@yourbusiness.com"

# Option 1: Set variables directly (less secure for API keys)
[vars]
NOTIFICATION_EMAIL = "Leads@momentumbusinesscapital.com"  # Primary recipient
NOTIFICATION_EMAIL_2 = "support@joinmbc.com"              # Secondary recipient
FROM_EMAIL = "funding@momentumbusiness.capital"           # From address

# Option 2: Use wrangler secrets for sensitive data (recommended)
# Run these commands to set secrets securely:
# wrangler secret put SENDGRID_API_KEY
# wrangler secret put NOTIFICATION_EMAIL
# wrangler secret put FROM_EMAIL 