name = "mbc-fullstack"
main = "src/worker.ts"
compatibility_date = "2024-01-15"

[site]
bucket = "../dist"

[vars]
NOTIFICATION_EMAIL = "Leads@momentumbusinesscapital.com"
NOTIFICATION_EMAIL_2 = "support@joinmbc.com"
FROM_EMAIL = "support@joinmbc.com"
# Do NOT put SENDGRID_API_KEY here—set it as a secret in the Cloudflare dashboard!

[env.production]
name = "mbc-fullstack"
route = "app.momentumbusiness.capital/*"

[observability.logs]
enabled = true
invocation_logs = true
