name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy to Production Environment
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Clear npm cache and install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Build application for production
        run: npm run build
        env:
          NODE_ENV: production

      - name: Update wrangler config for production environment
        run: |
          # Update the generated wrangler.json to use production worker name
          cd dist
          if [ -f wrangler.json ]; then
            # Use node to update the JSON file
            node -e "
              const fs = require('fs');
              const config = JSON.parse(fs.readFileSync('wrangler.json', 'utf8'));
              config.name = 'momentum-business-capital-landing';
              config.vars = config.vars || {};
              config.vars.ENVIRONMENT = 'production';
              fs.writeFileSync('wrangler.json', JSON.stringify(config, null, 2));
            "
          fi

      - name: Deploy to Cloudflare Workers (Production)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: './dist'
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY_PROD }}

      - name: Create deployment notification
        run: |
          echo "🎉 Production deployment successful!" 
          echo "Live URL: https://momentum-business-capital-landing.shy-math-4d31.workers.dev"
          echo "Deployed from commit: ${{ github.sha }}" 